import a1 from './a.jpg'
import b1 from './b.jpg'
import c1 from './c.jpg'
import d1 from './d.jpg'
import e1 from './e.jpg'
import f1 from './f.jpg'
import g1 from './g.jpg'
import h1 from './h.jpg'
import a2 from  './a2.jpg'
import b2 from  './b2.jpg'
import c2 from  './c2.jpg'
import d2 from  './d2.jpg'
import e2 from  './e2.jpg'
import f2 from  './f2.jpg'
import g2 from  './g2.jpg'
import h2 from  './h2.jpg'
import a3 from  './a3.jpg'
import b3 from  './b3.jpg'
import c3 from  './c3.jpg'
import d3 from  './d3.jpg'
import e3 from  './e3.jpg'
import f3 from  './f3.jpeg'
import g3 from  './g3.jpeg'
import h3 from  './h3.jpeg'

export{a1,b1,c1,d1,e1,f1,g1,h1,a2,b2,c2,d2,e2,f2,g2,h2,a3,b3,c3,d3,e3,f3,g3,h3}